<div id="menu">
	<a href="<?php echo $this->url(array('controller' => 'mysql', 'action' => 'list', 'table' => 'tag'), null, true); ?>">Tag</a>
	<a href="<?php echo $this->url(array('controller' => 'transmit'), null, true); ?>">Transmit</a>
	<a href="<?php echo $this->url(array('controller' => 'shell'), null, true); ?>">Shell</a>
	<a href="<?php echo $this->url(array('controller' => 'task'), null, true); ?>">Task</a>
</div>
